from typing import Any, Optional

TOKEN_TYPE_INTEGER_CONST = "INTEGER_CONST"
TOKEN_TYPE_REAL_CONST = "REAL_CONST"
TOKEN_TYPE_PLUS = "PLUS"
TOKEN_TYPE_MINUS = "MINUS"
TOKEN_TYPE_STAR = "STAR"
TOKEN_TYPE_SLASH = "SLASH"
TOKEN_TYPE_LEFT_PAREN = "LEFT_PAREN"
TOKEN_TYPE_RIGHT_PAREN = "RIGHT_PAREN"
TOKEN_TYPE_EOF = "EOF"
TOKEN_TYPE_BEGIN = "BEGIN"
TOKEN_TYPE_END = "END"
TOKEN_TYPE_DOT = "DOT"
TOKEN_TYPE_ID = "ID"
TOKEN_TYPE_ASSIGN = "ASSIGN"
TOKEN_TYPE_SEMI = "SEMI"
TOKEN_TYPE_VAR = "VAR"
TOKEN_TYPE_COMMA = "COMMA"
TOKEN_TYPE_COLON = "COLON"
TOKEN_TYPE_INTEGER = "INTEGER"
TOKEN_TYPE_REAL = "REAL"
TOKEN_TYPE_INTEGER_DIV = "DIV"
TOKEN_TYPE_PROGRAM = "PROGRAM"
TOKEN_TYPE_PROCEDURE = "PROCEDURE"

class Token:
    def __init__(self, type: str, value: Optional[Any]):
        self.type = type
        self.value = value

    def __str__(self):
        return f"Token({self.type}, {self.value})"

    def __repr__(self):
        return str(self)
